spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=billingdb;encrypt=true;trustServerCertificate=true
spring.datasource.username=SEU_USUARIO
spring.datasource.password=SUA_SENHA
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update

twilio.account.sid=SEU_TWILIO_ACCOUNT_SID
twilio.auth.token=SEU_TWILIO_AUTH_TOKEN
twilio.whatsapp.number=whatsapp:+SEU_NUMERO
mercado.pago.access.token=SEU_MERCADO_PAGO_ACCESS_TOKEN
empresa.nome=Sua Empresa Ltda
cnpj=12.345.678/0001-99
chave.pix=cnpj@empresa.com